apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-configs'
  labels:
    katenary.io/component: active-directory
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    use-subpath: "true"
data:
  users.ldif: {{ .Values.ldapConfig }}